language: csharp
sudo: required
dist: trusty
addons:
  apt:
    packages:
    - gettext
    - libcurl4-openssl-dev
    - libicu-dev
    - libssl-dev
    - libunwind8
    - zlib1g
mono:
  - 4.0.5
os:
  - linux
  - osx
osx_image: xcode7.1
install:
  - curl -sSL https://github.com/libuv/libuv/archive/v1.4.2.tar.gz | tar zxfv - -C /tmp && cd /tmp/libuv-1.4.2/
  - sh autogen.sh
  - ./configure --prefix=$HOME/libuvinstall
  - make
  - make install
  - export LD_LIBRARY_PATH="$HOME/libuvinstall/lib"
  - cd $OLDPWD
before_script:
  - npm install -g bower
  - npm install -g gulp
branches:
  only:
    - master
    - release
    - dev
    - /^(.*\/)?ci-.*$/
before_install:
  - if test "$TRAVIS_OS_NAME" == "osx"; then brew update; brew install openssl; brew link --force openssl; fi
script:
  - ./build.sh --quiet verify
notifications:
  webhooks:
    secure: "VASW9+87Yl4roIDDw/+4DZYCIqAzdATEk4w52TIWDdG1mmqV1Z83Iol2sQdAViUctXzxIto/OibCGzBlsUFp8J+J6Yw+BOng4jrOTbFMguQw+/UMhRmtLIMu/eWJMiFr7Homjan5owu1TZmfIkR8XYxXyeY4ITJqJkkDmq53eHE="
  on_success: always
  on_failure: always
  on_start: always
env:
  - KOREBUILD_TEST_SKIPMONO=1  